# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 300
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_300.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3
 
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 350
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_350.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 400
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_400.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 450
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_450.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 500
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_500.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 550
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_550.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 600
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_600.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 650
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_650.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 700
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_bias_batch_4_lamb_0.1_num_smallest_700.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3
# lamda 50
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 300
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_300.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 350
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_350.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 400
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_400.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 450
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_450.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 500
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_500.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 40 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 550
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_550.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 600
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_600.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 650
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_650.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 700
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_bias_batch_4_lamb_0.1_num_smallest_700.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# 加上true
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 300
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_4_lamb_0.1_num_smallest_300.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 350
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_4_lamb_0.1_num_smallest_350.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 400
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_400.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 450
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_450.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 500
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_500.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 550
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_550.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 600
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_600.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 650
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_650.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_50_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 50 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 700
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_50_true_bias_batch_1_lamb_0.1_num_smallest_700.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3



# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 300
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_300.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 350
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_350.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 400
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_400.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 450
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_450.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 500
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_500.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 550
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_550.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 600
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_600.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 650
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_650.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 40 --device cuda:3

# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alpha3.py --concepts 'professions200' --concept_type 'bias_profession' --guided_concepts 'bias' --add_prompts True --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100_true.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/art_erase/debias/debias_200_lamda_100.txt --lamda 100 --coco_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/extracted_subjects_big_only_20000.csv --device 3 --num_smallest_singular 700
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval-scripts/generate_pro_images.py --model_name debias_200_lamda_100_true_bias_batch_1_lamb_0.1_num_smallest_700.pt --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor_origin.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/bias --num_samples 20 --device cuda:3
# lamda 50


# lamda 加True