# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/1000_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/1000_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_1000/null_space_project_subject_1000_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/2000_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/2000_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_2000/null_space_project_subject_2000_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/3000_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/3000_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_3000/null_space_project_subject_3000_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/4000_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/4000_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_4000/null_space_project_subject_4000_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/5000_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/5000_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_5000/null_space_project_subject_5000_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/100_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/100_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_100/null_space_project_subject_100_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/500_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/500_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_500/null_space_project_subject_500_3_300.pt
# python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/train_unbias/train_bias_alphaedit.py --concepts 'doctor' --guided_concepts 'bias' --add_prompts True --device 0 --concept_type 'bias_profession' --model_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/10_3.pt --concepts_save_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/alpha_bias/10_3.txt --projection_path /mnt/bn/intern-disk/mlx/users/wrp/uce_nullspace/model_save/nullspace_project/input_10/null_space_project_subject_10_3_300.pt

python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 1000_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 2000_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 3000_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 4000_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 5000_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 100_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 500_3.pt --num_samples 20
python /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/eval_scripts_1/generate-images.py --prompts_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor/doctor.csv --save_path /mlx_devbox/users/wangruipeng/playground/paper_run/uce_nullspace/unified-concept-editing-main/data/profession/doctor --model_name 10_3.pt --num_samples 20